apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: ipv4networkallocations.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: IPv4NetworkAllocation
    plural: ipv4networkallocations
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        description: |
          IPv4NetworkAllocation bridges IPAM and Network by creating per-network pools
          and reserving IPv4 CIDRs via VPCIpamPoolCidrAllocation. Exposes allocated CIDRs
          in status for Network to consume.
        required:
        - spec
        properties:
          spec:
            type: object
            description: Desired state for the IPv4 network allocation.
            required:
            - regionalPoolId
            - scopeId
            - region
            properties:
              managementPolicies:
                type: array
                description: Management operations permitted on composed resources.
                items:
                  type: string
                  enum:
                  - "*"
                  - Create
                  - Observe
                  - Update
                  - Delete
                  - LateInitialize
                default:
                - "*"
              providerConfigRef:
                type: object
                description: Reference to the AWS ProviderConfig.
                properties:
                  name:
                    type: string
                    description: Name of the ProviderConfig. Defaults to "default".
                  kind:
                    type: string
                    description: Kind of the ProviderConfig. Defaults to "ProviderConfig".
                    default: ProviderConfig
              regionalPoolId:
                type: string
                description: |
                  ID of the regional IPAM pool to allocate from (from aws-ipam status).
                  This pool should be the regional pool created by aws-ipam.
              scopeId:
                type: string
                description: |
                  IPAM scope ID (from aws-ipam status.ipam.privateDefaultScopeId).
                  Required for creating child pools.
              region:
                type: string
                description: AWS region where the pool resources are managed.
              locale:
                type: string
                description: |
                  AWS region where CIDRs from these pools can be allocated.
                  When set, only VPCs in this region can use addresses from the pools.
                  Leave unset to inherit from parent pool or let AWS default.
              tags:
                type: object
                description: Additional tags to apply to AWS resources. Merged with default tags.
                additionalProperties:
                  type: string
              vpc:
                type: object
                description: VPC sizing configuration.
                properties:
                  netmaskLength:
                    type: integer
                    description: Netmask length for the VPC CIDR block. Defaults to 16.
                    default: 16
                    minimum: 16
                    maximum: 28
              subnets:
                type: object
                description: Subnet layout configuration.
                properties:
                  availabilityZones:
                    type: array
                    description: Availability zone suffixes (a, b, c). Defaults to [a, b, c].
                    items:
                      type: string
                    default:
                    - a
                    - b
                    - c
                  public:
                    type: object
                    description: Public subnet configuration.
                    properties:
                      enabled:
                        type: boolean
                        description: Whether to create public subnets. Defaults to true.
                        default: true
                      netmaskLength:
                        type: integer
                        description: Netmask length for public subnets. Defaults to 24.
                        minimum: 20
                        maximum: 24
                        default: 24
                  private:
                    type: object
                    description: Private subnet configuration.
                    properties:
                      enabled:
                        type: boolean
                        description: Whether to create private subnets. Defaults to true.
                        default: true
                      netmaskLength:
                        type: integer
                        description: Netmask length for private subnets. Defaults to 20.
                        minimum: 20
                        maximum: 24
                        default: 20
          status:
            type: object
            description: Observed state of the IPv4 network allocation.
            properties:
              ready:
                type: boolean
                description: True when all allocations are complete.
              cidr:
                type: string
                description: Allocated VPC CIDR block.
              vpcPoolId:
                type: string
                description: ID of the VPC IPAM pool.
              subnetPoolId:
                type: string
                description: ID of the subnet IPAM pool.
              subnets:
                type: object
                description: Map of subnet name to allocated CIDR.
                x-kubernetes-preserve-unknown-fields: true
