// Package v1alpha1 contains generated models.
//
// Code generated by github.com/upbound/up version v0.41.0 DO NOT EDIT.
package v1alpha1

import (
	metav1 "dev.upbound.io/models/io/k8s/meta/v1"
	"time"
)

// Use time to avoid unused import errors.
var (
	_ *time.Time = nil
)

// Defines values for IPV4NetworkAllocationAPIVersion.
const (
	IPV4NetworkAllocationAPIVersionawsHopsOpsComAiV1Alpha1 IPV4NetworkAllocationAPIVersion = "aws.hops.ops.com.ai/v1alpha1"
)

// Defines values for IPV4NetworkAllocationKind.
const (
	IPV4NetworkAllocationKindIPV4NetworkAllocation IPV4NetworkAllocationKind = "IPV4NetworkAllocation"
)

// Defines values for IPV4NetworkAllocationSpecCrossplaneCompositionUpdatePolicy.
const (
	IPV4NetworkAllocationSpecCrossplaneCompositionUpdatePolicyAutomatic IPV4NetworkAllocationSpecCrossplaneCompositionUpdatePolicy = "Automatic"
	IPV4NetworkAllocationSpecCrossplaneCompositionUpdatePolicyManual    IPV4NetworkAllocationSpecCrossplaneCompositionUpdatePolicy = "Manual"
)

// Defines values for IPV4NetworkAllocationSpecManagementPoliciesItem.
const (
	IPV4NetworkAllocationSpecManagementPoliciesItemIPV4NetworkAllocationSpecManagementPoliciesItem               IPV4NetworkAllocationSpecManagementPoliciesItem = "*"
	IPV4NetworkAllocationSpecManagementPoliciesItemIPV4NetworkAllocationSpecManagementPoliciesItemCreate         IPV4NetworkAllocationSpecManagementPoliciesItem = "Create"
	IPV4NetworkAllocationSpecManagementPoliciesItemIPV4NetworkAllocationSpecManagementPoliciesItemDelete         IPV4NetworkAllocationSpecManagementPoliciesItem = "Delete"
	IPV4NetworkAllocationSpecManagementPoliciesItemIPV4NetworkAllocationSpecManagementPoliciesItemLateInitialize IPV4NetworkAllocationSpecManagementPoliciesItem = "LateInitialize"
	IPV4NetworkAllocationSpecManagementPoliciesItemIPV4NetworkAllocationSpecManagementPoliciesItemObserve        IPV4NetworkAllocationSpecManagementPoliciesItem = "Observe"
	IPV4NetworkAllocationSpecManagementPoliciesItemIPV4NetworkAllocationSpecManagementPoliciesItemUpdate         IPV4NetworkAllocationSpecManagementPoliciesItem = "Update"
)

// AiComOpsHopsAwsV1Alpha1IPV4NetworkAllocation IPV4NetworkAllocation bridges IPAM and Network by creating per-network pools
// and reserving IPv4 CIDRs via VPCIpamPoolCidrAllocation. Exposes allocated CIDRs
// in status for Network to consume.
type AiComOpsHopsAwsV1Alpha1IPV4NetworkAllocation = IPV4NetworkAllocation

// IPV4NetworkAllocationAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type IPV4NetworkAllocationAPIVersion string

// IPV4NetworkAllocationKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type IPV4NetworkAllocationKind string

// IPV4NetworkAllocationSpecAws AWS configuration.
type IPV4NetworkAllocationSpecAws struct {
	// ProviderConfig ProviderConfig for AWS API operations. Defaults to "default".
	ProviderConfig *string `json:"providerConfig,omitempty"`

	// Region AWS region for the allocation. Defaults to us-east-1.
	Region *string `json:"region,omitempty"`
}

// IPV4NetworkAllocationSpecCrossplaneCompositionRef defines model for .
type IPV4NetworkAllocationSpecCrossplaneCompositionRef struct {
	Name *string `json:"name,omitempty"`
}

// IPV4NetworkAllocationSpecCrossplaneCompositionRevisionRef defines model for .
type IPV4NetworkAllocationSpecCrossplaneCompositionRevisionRef struct {
	Name *string `json:"name,omitempty"`
}

// IPV4NetworkAllocationSpecCrossplaneCompositionRevisionSelector defines model for .
type IPV4NetworkAllocationSpecCrossplaneCompositionRevisionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// IPV4NetworkAllocationSpecCrossplaneCompositionSelector defines model for .
type IPV4NetworkAllocationSpecCrossplaneCompositionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// IPV4NetworkAllocationSpecCrossplaneCompositionUpdatePolicy defines model for ai.com.ops.hops.aws.v1alpha1.IPV4NetworkAllocation.spec.crossplane.compositionUpdatePolicy.
type IPV4NetworkAllocationSpecCrossplaneCompositionUpdatePolicy string

// IPV4NetworkAllocationSpecCrossplaneResourceRefsItem defines model for .
type IPV4NetworkAllocationSpecCrossplaneResourceRefsItem struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// IPV4NetworkAllocationSpecCrossplane Configures how Crossplane will reconcile this composite resource
type IPV4NetworkAllocationSpecCrossplane struct {
	CompositionRef              *IPV4NetworkAllocationSpecCrossplaneCompositionRef              `json:"compositionRef,omitempty"`
	CompositionRevisionRef      *IPV4NetworkAllocationSpecCrossplaneCompositionRevisionRef      `json:"compositionRevisionRef,omitempty"`
	CompositionRevisionSelector *IPV4NetworkAllocationSpecCrossplaneCompositionRevisionSelector `json:"compositionRevisionSelector,omitempty"`
	CompositionSelector         *IPV4NetworkAllocationSpecCrossplaneCompositionSelector         `json:"compositionSelector,omitempty"`
	CompositionUpdatePolicy     *IPV4NetworkAllocationSpecCrossplaneCompositionUpdatePolicy     `json:"compositionUpdatePolicy,omitempty"`
	ResourceRefs                *[]IPV4NetworkAllocationSpecCrossplaneResourceRefsItem          `json:"resourceRefs,omitempty"`
}

// IPV4NetworkAllocationSpecManagementPoliciesItem defines model for ai.com.ops.hops.aws.v1alpha1.IPV4NetworkAllocation.spec.managementPolicies.
type IPV4NetworkAllocationSpecManagementPoliciesItem string

// IPV4NetworkAllocationSpecSubnetsTypesPrivate Private subnet configuration.
type IPV4NetworkAllocationSpecSubnetsTypesPrivate struct {
	// NetmaskLength Netmask length for private subnets. Defaults to 20.
	NetmaskLength *int `json:"netmaskLength,omitempty"`
}

// IPV4NetworkAllocationSpecSubnetsTypesPublic Public subnet configuration.
type IPV4NetworkAllocationSpecSubnetsTypesPublic struct {
	// NetmaskLength Netmask length for public subnets. Defaults to 24.
	NetmaskLength *int `json:"netmaskLength,omitempty"`
}

// IPV4NetworkAllocationSpecSubnetsTypes Subnet type configurations.
type IPV4NetworkAllocationSpecSubnetsTypes struct {
	// Private Private subnet configuration.
	Private *IPV4NetworkAllocationSpecSubnetsTypesPrivate `json:"private,omitempty"`

	// Public Public subnet configuration.
	Public *IPV4NetworkAllocationSpecSubnetsTypesPublic `json:"public,omitempty"`
}

// IPV4NetworkAllocationSpecSubnets Subnet layout configuration.
type IPV4NetworkAllocationSpecSubnets struct {
	// AvailabilityZones Availability zone suffixes (a, b, c). Defaults to [a, b, c].
	AvailabilityZones *[]string `json:"availabilityZones,omitempty"`

	// Types Subnet type configurations.
	Types *IPV4NetworkAllocationSpecSubnetsTypes `json:"types,omitempty"`
}

// IPV4NetworkAllocationSpecVpc VPC sizing configuration.
type IPV4NetworkAllocationSpecVpc struct {
	// NetmaskLength Netmask length for the VPC CIDR block. Defaults to 16.
	NetmaskLength *int `json:"netmaskLength,omitempty"`
}

// IPV4NetworkAllocationSpec Desired state for the IPv4 network allocation.
type IPV4NetworkAllocationSpec struct {
	// Aws AWS configuration.
	Aws *IPV4NetworkAllocationSpecAws `json:"aws,omitempty"`

	// Crossplane Configures how Crossplane will reconcile this composite resource
	Crossplane *IPV4NetworkAllocationSpecCrossplane `json:"crossplane,omitempty"`

	// ManagementPolicies Management operations permitted on composed resources.
	ManagementPolicies *[]IPV4NetworkAllocationSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// RegionalPoolID ID of the regional IPAM pool to allocate from (from aws-ipam status).
	// This pool should be the regional pool created by aws-ipam.
	RegionalPoolID *string `json:"regionalPoolId,omitempty"`

	// Subnets Subnet layout configuration.
	Subnets *IPV4NetworkAllocationSpecSubnets `json:"subnets,omitempty"`

	// Vpc VPC sizing configuration.
	Vpc *IPV4NetworkAllocationSpecVpc `json:"vpc,omitempty"`
}

// IPV4NetworkAllocationStatusConditionsItem defines model for .
type IPV4NetworkAllocationStatusConditionsItem struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	ObservedGeneration *int64     `json:"observedGeneration,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// IPV4NetworkAllocationStatusCrossplaneConnectionDetails defines model for .
type IPV4NetworkAllocationStatusCrossplaneConnectionDetails struct {
	LastPublishedTime *time.Time `json:"lastPublishedTime,omitempty"`
}

// IPV4NetworkAllocationStatusCrossplane Indicates how Crossplane is reconciling this composite resource
type IPV4NetworkAllocationStatusCrossplane struct {
	ConnectionDetails *IPV4NetworkAllocationStatusCrossplaneConnectionDetails `json:"connectionDetails,omitempty"`
}

// IPV4NetworkAllocationStatusSubnets Map of subnet name to allocated CIDR.
type IPV4NetworkAllocationStatusSubnets = map[string]interface{}

// IPV4NetworkAllocationStatus Observed state of the IPv4 network allocation.
type IPV4NetworkAllocationStatus struct {
	// Cidr Allocated VPC CIDR block.
	Cidr *string `json:"cidr,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]IPV4NetworkAllocationStatusConditionsItem `json:"conditions,omitempty"`

	// Crossplane Indicates how Crossplane is reconciling this composite resource
	Crossplane *IPV4NetworkAllocationStatusCrossplane `json:"crossplane,omitempty"`

	// PrivatePoolID ID of the private subnet IPAM pool.
	PrivatePoolID *string `json:"privatePoolId,omitempty"`

	// PublicPoolID ID of the public subnet IPAM pool.
	PublicPoolID *string `json:"publicPoolId,omitempty"`

	// Ready True when all allocations are complete.
	Ready *bool `json:"ready,omitempty"`

	// Subnets Map of subnet name to allocated CIDR.
	Subnets *IPV4NetworkAllocationStatusSubnets `json:"subnets,omitempty"`

	// VpcPoolID ID of the VPC IPAM pool.
	VpcPoolID *string `json:"vpcPoolId,omitempty"`
}

// IPV4NetworkAllocation IPV4NetworkAllocation bridges IPAM and Network by creating per-network pools
// and reserving IPv4 CIDRs via VPCIpamPoolCidrAllocation. Exposes allocated CIDRs
// in status for Network to consume.
type IPV4NetworkAllocation struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *IPV4NetworkAllocationAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *IPV4NetworkAllocationKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec Desired state for the IPv4 network allocation.
	Spec *IPV4NetworkAllocationSpec `json:"spec,omitempty"`

	// Status Observed state of the IPv4 network allocation.
	Status *IPV4NetworkAllocationStatus `json:"status,omitempty"`
}

// AiComOpsHopsAwsV1Alpha1IPV4NetworkAllocationList IPV4NetworkAllocationList is a list of IPV4NetworkAllocation
type AiComOpsHopsAwsV1Alpha1IPV4NetworkAllocationList = IPV4NetworkAllocationList

// IPV4NetworkAllocationList IPV4NetworkAllocationList is a list of IPV4NetworkAllocation
type IPV4NetworkAllocationList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of ipv4networkallocations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]AiComOpsHopsAwsV1Alpha1IPV4NetworkAllocation `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
