apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: IPv4NetworkAllocation
metadata:
  name: dev-west
  namespace: infra
spec:
  # Regional pool ID from aws-ipam status
  regionalPoolId: ipam-pool-0123456789abcdef0
  # IPAM scope ID from aws-ipam status.ipam.privateDefaultScopeId
  scopeId: ipam-scope-0123456789abcdef0

  providerConfigRef:
    name: default

  aws:
    region: us-west-2
    # Custom tags merged with defaults (hops=true, managed-by=crossplane)
    tags:
      environment: dev
      team: platform

  # Smaller VPC for dev
  vpc:
    netmaskLength: 20

  # Only 2 AZs, custom subnet sizes
  subnets:
    availabilityZones:
    - a
    - b
    public:
      netmaskLength: 24
    private:
      netmaskLength: 20
