# generated by datamodel-codegen:
#   filename:  workdir/aws_hops_ops_com_ai_v1alpha1_ipv4networkallocation.yaml

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, conint

from .......io.k8s.apimachinery.pkg.apis.meta import v1


class Aws(BaseModel):
    providerConfig: Optional[str] = None
    """
    ProviderConfig for AWS API operations. Defaults to "default".
    """
    region: Optional[str] = None
    """
    AWS region for the allocation. Defaults to us-east-1.
    """


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: Dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: Dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: Optional[str] = None


class Crossplane(BaseModel):
    compositionRef: Optional[CompositionRef] = None
    compositionRevisionRef: Optional[CompositionRevisionRef] = None
    compositionRevisionSelector: Optional[CompositionRevisionSelector] = None
    compositionSelector: Optional[CompositionSelector] = None
    compositionUpdatePolicy: Optional[Literal['Automatic', 'Manual']] = None
    resourceRefs: Optional[List[ResourceRef]] = None


class Private(BaseModel):
    netmaskLength: Optional[conint(ge=16, le=28)] = 20
    """
    Netmask length for private subnets. Defaults to 20.
    """


class Public(BaseModel):
    netmaskLength: Optional[conint(ge=16, le=28)] = 24
    """
    Netmask length for public subnets. Defaults to 24.
    """


class Types(BaseModel):
    private: Optional[Private] = None
    """
    Private subnet configuration.
    """
    public: Optional[Public] = None
    """
    Public subnet configuration.
    """


class Subnets(BaseModel):
    availabilityZones: Optional[List[str]] = ['a', 'b', 'c']
    """
    Availability zone suffixes (a, b, c). Defaults to [a, b, c].
    """
    types: Optional[Types] = None
    """
    Subnet type configurations.
    """


class Vpc(BaseModel):
    netmaskLength: Optional[conint(ge=8, le=28)] = 16
    """
    Netmask length for the VPC CIDR block. Defaults to 16.
    """


class Spec(BaseModel):
    aws: Optional[Aws] = None
    """
    AWS configuration.
    """
    crossplane: Optional[Crossplane] = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    managementPolicies: Optional[
        List[Literal['*', 'Create', 'Observe', 'Update', 'Delete', 'LateInitialize']]
    ] = ['*']
    """
    Management operations permitted on composed resources.
    """
    regionalPoolId: str
    """
    ID of the regional IPAM pool to allocate from (from aws-ipam status).
    This pool should be the regional pool created by aws-ipam.

    """
    subnets: Optional[Subnets] = None
    """
    Subnet layout configuration.
    """
    vpc: Optional[Vpc] = None
    """
    VPC sizing configuration.
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    message: Optional[str] = None
    observedGeneration: Optional[int] = None
    reason: str
    status: str
    type: str


class ConnectionDetails(BaseModel):
    lastPublishedTime: Optional[datetime] = None


class CrossplaneModel(BaseModel):
    connectionDetails: Optional[ConnectionDetails] = None


class Status(BaseModel):
    cidr: Optional[str] = None
    """
    Allocated VPC CIDR block.
    """
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    crossplane: Optional[CrossplaneModel] = None
    """
    Indicates how Crossplane is reconciling this composite resource
    """
    privatePoolId: Optional[str] = None
    """
    ID of the private subnet IPAM pool.
    """
    publicPoolId: Optional[str] = None
    """
    ID of the public subnet IPAM pool.
    """
    ready: Optional[bool] = None
    """
    True when all allocations are complete.
    """
    subnets: Optional[Dict[str, Any]] = None
    """
    Map of subnet name to allocated CIDR.
    """
    vpcPoolId: Optional[str] = None
    """
    ID of the VPC IPAM pool.
    """


class IPV4NetworkAllocation(BaseModel):
    apiVersion: Optional[Literal['aws.hops.ops.com.ai/v1alpha1']] = (
        'aws.hops.ops.com.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['IPV4NetworkAllocation']] = 'IPV4NetworkAllocation'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    Desired state for the IPv4 network allocation.
    """
    status: Optional[Status] = None
    """
    Observed state of the IPv4 network allocation.
    """


class IPV4NetworkAllocationList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[IPV4NetworkAllocation]
    """
    List of ipv4networkallocations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """